### ISSUE TITLE
unable to access setup

### ISSUE THREAD

**Issue by ronwell74** [jghaanstra/android.ipwebcam#11]
after installing the app, the app has a pause icon that won't go away, and unable to access the setttings screen all i get is white page.

**Comment by jghaanstra** [comment]
Thanx for reportting, will fix it right away.

**Comment by ronwell74** [comment]
could you also create some instructions on how to set up the app on the
tablet/phone. i haven't been able to find any
thank you.

-------------------------------------------- :-)

Aaron .L .Powell

25/328 Fullarton rd.

Fullarton South Australia 5063

ph: 0402675551

email: aaronp.74@gmail.com

-------------------------------------------- :-)

**Comment by jghaanstra** [comment]
Fixed with release 3.0.3.

Instructions can be found here: https://community.athom.com/t/app-android-ip-webcam-needs-other-developer/122
