### ISSUE TITLE
Sinds 2.1.2 geen snapshot meer

### ISSUE THREAD

**Issue by bramweer** [jghaanstra/android.ipwebcam#2]
Werkte perfect maar ontvang sinds 2.1.2 geen snapshot meer. Wel testmail. Smartphone opnieuw toegevoegd helpt ook niet.

**Comment by jghaanstra** [comment]
Ik heb het zojuist getest en het werkt hier prima op 2.1.2. Het zit dus ergens in je eigen configuratie.

Kan Homey de Android IP Webcam bereiken (geen rood uitroepteken bij het device in Homey)? Zo ja, krijg je een foutmelding of een groen vinkje als je de "email live snapshot" actie kaart test. Bij een foutmelding, wat is dan de foutmelding. Indien je hier een groen vinkje krijgt zit het probleem niet in mijn app maar ergens nadat de email met snapshot is verzonden, bijvoorbeeld een block door een spam filter.

Zonder meer informatie kan ik hier niet veel aan doen.

**Comment by bramweer** [comment]
Beste jelger aller eerst complimenten voor je app.
Testmail gaat goed in je app komt binnen.
Rode uitroepteken is inderdaad aanwezig maar dat is er ook toen ie het nog
wel deed. Dat vond ik al vreemd maar het werkte gewoon.
Werkte perfect, na update vannacht niet meer.
Alles gereset en toestel opnieuw aangemeld. In app beeld test werkt.
Dus beeld test werkt en email test werkt.
Wel uitroepteken maar dat had ie bij werkende functie ook.
Nog suggesties voor mij?


Groeten Bram

Op wo 8 mei 2019 09:05 schreef Jelger Haanstra <notifications@github.com>:

**Comment by jghaanstra** [comment]
Het rode uitroepteken betekent dat er iets mis is met de configuratie van IP Webcam op je telefoon. Het zou heel bijzonder zijn als het voor 2.1.2 gewerkt heeft terwijl het apparaat in Homey een rood uitroepteken had. Dit zal in ieder geval de reden zijn waarom het niet goed werkt op 2.1.2. Je zult alle stappen van de installatie nog een keer goed bij langs moeten lopen om ervoor te zorgen dat de configuratie van IP Webcam goed staat (data logging voor de juiste events en sound en motion detection geactiveerd). Ben je van mening dat alles correct is geconfigureerd dan kan je de output van deze link in een zipfile stoppen en hier posten, dan kan ik zien welke data ontbreekt waardoor de webcam een rood uitroepteken geeft.

 http://<<your_ip_webcamip>>:<<ip_webcam_port>>/sensors.json

**Comment by bramweer** [comment]
Gevonden 1 vinkje verkeerd, bedankt

 

-- 
Groeten Bram



 

Van: Jelger Haanstra [mailto:notifications@github.com] 
Verzonden: woensdag 8 mei 2019 10:28
Aan: jghaanstra/android.ipwebcam
CC: bramweer; Author
Onderwerp: Re: [jghaanstra/android.ipwebcam] Sinds 2.1.2 geen snapshot meer (#2)

 

Closed #2 <https://github.com/jghaanstra/android.ipwebcam/issues/2> .
