### ISSUE TITLE
Missing sensor data: light sensor

### ISSUE THREAD

**Issue by ncickc** [jghaanstra/android.ipwebcam#5]
Hi, 
I have used this app for quite some time now and was very happy with it. However, since the last update I'm not able to connect to my device anymore because of error message: 
"Sensor data ontbreekt: light"
I'm using an older phone for just the sound but this is not possible anymore.. is there any way to fix this please?

**Comment by jghaanstra** [comment]
I have just submitted release 1.3.2 to the app store that will fix this. Either wait for it to get approved or install it locallly.

https://github.com/jghaanstra/android.ipwebcam/releases/tag/1.3.2

**Comment by ncickc** [comment]
Perfect, thank you for the quick reply!
