### ISSUE TITLE
Exposure compensation

### ISSUE THREAD

**Issue by ChristerSjo** [jghaanstra/android.ipwebcam#7]
Is there any way to set the Exposure compensation in a Homey Flow?

**Comment by jghaanstra** [comment]
No but I assume you already knew that.

If your actual question is if this can be added? Probably yes. Just to be sure, you want to have a action card where you can manually set the exposure ns (looking at IP Webcam that would be within the range of 9384 - 15062000000 ns).

**Comment by ChristerSjo** [comment]
Hi,

 

I may have post it in wrong space when it was an request/wish 😉.

 

Depending on the light condition I think you have to elaborate with Night vision and Exposure. In the web interface you set it to between -3 and +3 not in ns. Either way the function would be appreciated. 

 

Best regards,

Christer

 

 

Från: Jelger Haanstra <notifications@github.com> 
Skickat: den 4 juni 2020 22:43
Till: jghaanstra/android.ipwebcam <android.ipwebcam@noreply.github.com>
Kopia: ChristerSjo <christer@sjostrom.biz>; Author <author@noreply.github.com>
Ämne: Re: [jghaanstra/android.ipwebcam] Exposure compensation (#7)

 

No but I assume you already knew that.

If your actual question is if this can be added? Probably yes. Just to be sure, you want to have a action card where you can manually set the exposure ns (looking at IP Webcam that would be within the range of 9384 - 15062000000 ns).

**Comment by jghaanstra** [comment]
Can you post a screenshot of which setting you want to control using a flow action card. I see there is a night vision exposure setting but I can only set it from 1 to 20.

I'm wondering if your device has other type of settings.
